# Calor específico de los sólidos

En 1819 Pierre Louis Dulong y Alexis Thérèse Petit establecieron que para casi todos los sólidos la capacidad calorífica esta dada por (ley de la Doulong-Petit),

$$
C= 3 k_{\rm B} \text{ por átomo}
$$

$$
C =3R
$$


donde $k_{\rm B}=1.380649\times 10^{-23} {\rm J}\cdot {\rm K}^{-1}$ es la constante de Boltzmann y $R=8.31446261815324 {\rm J}\cdot {\rm K}^{-1}\cdot {\rm mol}^{-1}$ es la constante molar de los gases. 

La ley de Doulong-Petit es válida para temperatura ambiente.

|Material|C/R|
|---|---|
|Aluminio (Al)|2.91|
|Antimonio (Sb)| 3.03|
|Cobre (Cu)| 2.94|
|Oro (Au)| 3.05|
|Plata (Ag)|2.99|
|Diamante (C)|0.735|

En 1896 Boltzmann intento dar sentido a la Ley de Doulong Petit. Planteó, cada átomo del sólido esta ligado a otros átomos entonces cada átomo es un oscilador armónico. Es decir, su energía esta dada por $mv^2/2+kx^2/2$ y utilizando el Teorema de equipartición de la energía, estableció que cada grado de libertad de oscilación contribuye en $k_{\rm B}T$ a la energía del sistema. En el caso de sólidos en tres dimensiones cada átomo contribuye a la energía en $3k_{\rm B}T$ por lo que

$$
C=\frac{d U}{d T } =3k_{\rm B} \text{ por átomo}
$$

::: {.column-margin}
En el caso de un gas, cada átomo contribuye a la energía en $mv_x^2/2+mv_y^2/2+mv_z^2/2$ por lo que siguiendo el Teorema de Equipartición de la energía la capacidad calorífica por átomo es $C=3k_{\rm B}/2$.
:::

En los inicios de los 1900, empezaron a realizar experimentos a bajas temperatura a algunos Kelvin. En 1907, Einstein intento explicar la capacidad calorífica a bajas temperaturas. Supuso que cada átomo es un oscilador armónico cuántico $E_n=\hbar \omega (n+1/2)$.

Boltzmann ya había establecido que la probabilidad de encontrar a un sistema a una energía $E_i$ era
$$
\text{Probabilidad }\propto e^{-\beta E_i}=e^{-E_i/k_{\rm B}T}
$$

Introduciendo la función de partición,

$$
Z_{\rm 1D} = \sum_{n\geq 0}  e^{-\beta \hbar \omega (n+1/2)} = \frac{e^{-\beta \hbar \omega/2}}{1-e^{-\beta \hbar \omega/2}}=\frac{1}{2\sinh (\beta\hbar\omega/2)}
$$

::: {.column-margin}
Recordemos que
$$
\sinh x=\frac{e^x-e^{-x}}{2}
$$
:::

podemos calcular el valor medio de la energía

$$
\langle E \rangle = -\frac{1}{Z_{1D}} \frac{\partial Z_{1D}}{\partial \beta} =\frac{\hbar \omega}{2} \coth(\beta \hbar \omega/2) = \hbar \omega \bigg[ n_{\rm B}(\beta \hbar \omega) +\frac{1}{2} \bigg]
$$

donde 
$$
n_{\rm B}(x)=\frac{1}{e^x-1}
$$

Entonces,

$$
C = \frac{\partial \langle E \rangle}{\partial T} = k_{\rm B} (\beta \hbar \omega)^2 \frac{e^{\beta \omega}}{(e^{\beta \hbar \omega}-1)^2}
$$

En el límite $T\to \infty$

$$
C=k_{\rm B} \; \Rightarrow \; \text{En tres dimensiones } C=3k_{\rm B}
$$

Aún existía la problemática de bajas temperaturas el modelo de Einstein establece que $C\sim e^{k_{\rm B}T}$ y experimentalmente se tenía que $C\sim T^3$. 

En 1912, Debye desarrolla un modelo para determinar la cpacidad calorífica a bajas temperaturas. Las oscilaciones (osciladores armónicos) son similares a las del sonido (ondas sonoras). En las ondas sonoras 
$$
\omega (k) = v| k| 
$$

donde $v$ es la rapidez del sonido. 

Análogo a Einstein

$$
\langle E\rangle = 3 \sum_{\vec{k}} \hbar \omega (\vec{k}) \bigg[ n_{\rm B}(\beta \hbar \omega) +1/2 \bigg]
$$

Sustituimos que $\omega (\vec{k})=vk$ y 
$$
\sum_{k_x} \to \frac{L}{2\pi} \int dk_x
$$

$$
\langle E\rangle = 3\frac{L^3}{(2\pi)^3} \int d\vec{k} \Bigg\{ \hbar\omega(\vec{k}) \bigg[  n_{\rm B}(\beta \hbar \omega) +1/2 \bigg] \Bigg\}
$$


$$
\int d\vec{k} \to 4\pi \int_0^{\infty} k^2 dk
$$

Utilizando que $k=\omega/v$ entonces $dk=\frac{1}{v}d\omega $

$$
\langle E \rangle = 3\bigg(  \frac{4\pi L^3}{(2\pi)^3} \bigg) \int_0^{\omega_{\rm corte}=\omega_{\rm D}} d\omega \Bigg\{  \omega^2\frac{1}{v^3}\hbar\omega \bigg[ n_{\rm B} +1/2\bigg] \Bigg\}
$$

$$
g(\omega) = L^3\bigg[ \frac{12\pi \omega^2}{(2\pi^3)v^3} \bigg]
$$

Utilizando la función Zeta de Riemann a $T_{\rm bajas}$

$$
\langle E \rangle = 9 N \frac{(k_{\rm B}T)^4}{\hbar \omega_{\rm D}} \frac{\pi^4}{15}\,; \; \omega_{\rm D} = 6\pi^2 n v^3
$$

donde $n$ es la densidad de átomos por unidad de volumen,

$$
\langle E \rangle = \frac{\partial \langle E \rangle }{\partial T } = Nk_{\rm B} \frac{k_{\rm B}T^3}{(\hbar \omega_{\rm D})^3} \frac{12 \pi^4}{5} \sim T^3
$$


|$T_{\rm Debye}\,[{\rm K}]$|Materiales|
|-|-|
|215 | Ag|
|315 | Cu|
| 1000| Si|
|1850| Diamante|

En los sólidos el calor es transportador por fonones y electrones.

Capacidad calorífica y conductividad térmica

Flujo de energía térmica, $j_{U}$, 

$$
j_{U}=-\kappa \frac{d T }{dx} 
$$

donde 
$$ 
\kappa = \frac{1}{3} C v \ell
$$
 es la conductividad térmica .

$$
v \sim \frac{d\omega}{dk}$
$$

$v$ es la rapidez de los fonones y $\ell$ camino libre medio de los fonones.
