project:
  type: book
  output-dir: docs

book:
  title: "Propiedades Físicas de los Sólidos"
  author: "JEBV"
  favicon: logoJEBV.png
  twitter-card: true
  chapters:
    - index.qmd
    - part: "U1. Estructuras periódicas"
      chapters:
        - 1_1_red.qmd
        - 1_2_celdaprimitiva.qmd
        - 1_3_vectoresred.qmd
        - 1_4_decorado.qmd
        - 1_5_construccionsistematica.qmd
        - 1_6_redreciproca.qmd
        - 1_7_fourier.qmd
        - 1_8_particulalibre.qmd
    - part: "U2. Vibraciones"
      chapters:
        - href: 2_1_molecula_H2.qmd
          text: "pyscf H2"
        - vibra1d.qmd
        - eqnonda.qmd
        - matrizdinamica.qmd
        - calorespecifico.qmd
    - part: "U3. Electrones"
    - part: "U4. Magnetismo"

format:
  html:
    theme: 
      light: minty
      dark: darkly
    fontsize: 1.0em
    css: styles.css
    code-fold: true
    code-summary: "Mostrar código"
    code-line-numbers: true
    code-copy: true
