project:
  type: book
  output-dir: docs

book:
  title: "PFS"
  favicon: logoJEBV.png
  twitter-card: true
  chapters:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: Acerca
    - part: "Vibraciones"
      chapters:
        - href: molecula_H2.qmd
          text: "pyscf H2"
        - vibra1d.qmd
        - eqnonda.qmd
        - matrizdinamica.qmd
        - calorespecifico.qmd
    - part: "Electrones"
format:
  html:
    theme: minty
    fontsize: 1.0em
    css: styles.css