project:
  type: website

website:
  title: "PFS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Acerca
      - href: vibra1d.qmd
        text: Vibraciones en una cadena

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



