project:
  type: book
  output-dir: docs

book:
  title: "PFS"
  favicon: logoJEBV.png
  twitter-card: true
  chapters:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: Acerca
    - href: vibra1d.qmd
      text: Vibraciones en una cadena

format:
  html:
    theme: minty
    css: styles.css



