# Matriz dinámica

**Objetivo:** describir de forma general cómo se mueven los átomos en un sólido

La estrategía general es: determinar la energía potencial, derivar las ecuaciones de movimiento y resolver las ecuaciones de movimiento buscando los modos normales.

## La energía potencial

$$
\newcommand{\vn}{\vec{n}}
\newcommand{\vm}{\vec{m}}
\newcommand{\vk}{\vec{k}}
\newcommand{\vRn}{\vec{R}_{\vn}}
\newcommand{\vRm}{\vec{R}_{\vm}}
\newcommand{\req}[3]{ r_{#1 #2 #3}}
\newcommand{\udes}[3]{ \delta r_{#1 #2 #3}}
$$

$$
\begin{align}
U &= U(\{ \text{posiciones: } \req{\vn}{\alpha}{i} + \udes{\vn}{\alpha}{i} \}) \\
&\approx U(\{  \req{\vn}{\alpha}{i} \})+ \sum_{\vn \alpha i} \frac{\partial U}{\partial \udes{\vn}{\alpha}{i}}\bigg|_{\req{\vn}{\alpha}{i}} \udes{\vn}{\alpha}{i} + \frac{1}{2} \sum_{\vn \alpha i } \sum_{\vm \beta j} \frac{\partial^2 U}{\partial \udes{\vn}{\alpha}{i} \partial \udes{\vm}{\beta}{j} }\bigg|_{ \req{\vn}{\alpha}{i} } \udes{\vn}{\alpha}{i} \udes{\vm}{\beta}{j}
\end{align}
$$

Introducimos la siguiente notación para las segundas derivadas,

$$
\frac{\partial^2 U}{\partial \udes{\vn}{\alpha}{i} \partial \udes{\vm}{\beta}{j} }\bigg|_{ \req{\vn}{\alpha}{i} } = U_{\vn \alpha i }^{\vm \beta j}\,,
$$
las cuales llamaremos constantes de acoplamiento. Entonces, la aproximación para la energía potencial es

$$
\begin{align}
U \approx U(\{  \req{\vn}{\alpha}{i} \}) + \frac{1}{2} \sum_{\vn \alpha i } \sum_{\vm \beta j} U_{\vn \alpha i }^{\vm \beta j} \udes{\vn}{\alpha}{i} \udes{\vm}{\beta}{j}
\end{align}
$$

La fuerza que se realiza sobre el átomo $\alpha$ en la celda $\vn$ en la dirección $i$ es,

$$
F_{\vn \alpha i }= -\frac{\partial U}{\partial  \udes{\vn}{\alpha}{i}} = \sum_{\vm \beta j} -U_{\vn \alpha i }^{\vm \beta j} \udes{\vm}{\beta}{j}
$$

Notamos que,

$$
-U_{\vn \alpha i }^{\vm \beta j} \udes{\vm}{\beta}{j}\,,
$$
es la fuerza que se realiza sobre el átomo $\alpha$ en la celda $\vn$ en la dirección $i$ al desplazar del equilibrio el átomo $\beta$ en la celda $\vm$ en la dirección $j$, $\udes{\vm}{\beta}{j}$.

Dada la simetría de traslación $U_{\vn \alpha i }^{\vm \beta j}$ sólo depende de la diferencia de las celdas; es decir, de $\vm-\vn$. Entonces,
$$
U_{\vec{0}\alpha i}^{ (\vm-\vn)\beta j } = U_{\vn \alpha i }^{\vm \beta j} 
$$

## Ecuaciones de movimiento

$$
M_\alpha \frac{d^2}{dt^2} \udes{\vn}{\alpha}{i} = -\sum_{\vm \beta j} U_{\vn \alpha i }^{\vm \beta j} \udes{\vm}{\beta}{j}
$$

$$
M_\alpha \frac{d^2}{dt^2} \udes{\vn}{\alpha}{i} + \sum_{\vm \beta j} U_{\vn \alpha i }^{\vm \beta j} \udes{\vm}{\beta}{j} = 0
$$

Notamos que tenemos $3rN$ ecuaciones de movimiento, donde el $3$ corresponde a las tres direcciones de movimiento en el espacio, $r$ es el número de átomos en la celda unitaria y $N$ son el número de celdas unitarias.

Proponemos una solución correspondiente a un modo normal,
$$
\udes{\vn}{\alpha}{i} = e^{i\omega t-i\vk\cdot \vRn }\bigg[  \frac{1}{\sqrt{M}_\alpha} u_{\alpha i} \bigg]
$$

Sustituimos en las ecuaciones de movimiento,
$$
-\omega^2 M_\alpha \bigg[  \frac{1}{\sqrt{M_\alpha}} u_{\alpha i} \bigg] + \sum_{\vm \beta j} U_{\vn \alpha i }^{\vm \beta j} e^{ i\vk \cdot (\vRn -\vRm) } \frac{1}{\sqrt{M}_\beta} u_{\beta j} = 0
$$

$$
-\omega^2 \sqrt{M}_\alpha u_{\alpha i} + \sum_{\beta j } \frac{1}{\sqrt{M}_\beta}\bigg[ \sum_{\vm} U_{\vn \alpha i }^{\vm \beta j} e^{ i\vk \cdot (\vRn -\vRm) }  \bigg] u_{\beta j} =0
$$

$$
-\omega^2  u_{\alpha i} + \sum_{\beta j } \frac{1}{\sqrt{M_\beta M_\alpha}}\bigg[ \sum_{\vm} U_{\vn \alpha i }^{\vm \beta j} e^{ i\vk \cdot (\vRn -\vRm) }  \bigg] u_{\beta j} =0
$$

Notamos que las ecuaciones anteriores son $3r$ para cada celda unitaria $\vn$ y dado que todas las celdas son iguales, podemos elegir arbitrariamente $\vn=\vec{0}$ y resolver. Entonces, dichas soluciones serán las mismas para todas. 

$$
-\omega^2  u_{\alpha i} + \sum_{\beta j } \frac{1}{\sqrt{M_\beta M_\alpha}}\bigg[ \sum_{\vm} U_{\vec{0} \alpha i }^{\vm \beta j} e^{-i\vk \cdot  \vRm }  \bigg] u_{\beta j} =0
$$

Las $3r$ ecuaciones podemos reescribirlas de forma matricial de la forma,
$$
\omega^2\left[\begin{array}{c}
u_{1 x}\\
u_{1 y}\\
u_{1 z}\\
\vdots \\
u_{r x}\\
u_{r y}\\
u_{r z}\\
\end{array}\right] = 
\bigg[ \frac{1}{\sqrt{M_\beta M_\alpha}} U_{\vec{0} \alpha i }^{\vm \beta j} e^{-i\vk \cdot  \vRm } \bigg]_{\alpha i,\beta j} \left[\begin{array}{c}
u_{1 x}\\
u_{1 y}\\
u_{1 z}\\
\vdots \\
u_{r x}\\
u_{r y}\\
u_{r z}\\
\end{array}\right]
$$

donde la matriz del lado derecho se llama matriz dinámica.


## Otra notación


Alternativamente,

$$
\sum_{\beta j } -\omega^2 \delta_{\alpha \beta}\delta_{ij} u_{\beta j}+ \sum_{\beta j } \frac{1}{\sqrt{M_\beta M_\alpha}}\bigg[ \sum_{\vm} U_{\vn \alpha i }^{\vm \beta j} e^{ i\vk \cdot (\vRn -\vRm) }  \bigg] u_{\beta j} =0
$$

